[build-system]
# Minimum requirements for the build system to execute.
# See https://github.com/scipy/scipy/pull/12940 for the AIX issue.
requires = [
    "setuptools",
    "wheel",
    "numpy",
    "pybind11",
    "pip"
]

build-backend = "setuptools.build_meta"
